server:
  port: 8763

spring:
  application:
    name: catalogue-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/productdb?serverTimezone=GMT
    username: go2shop
    password: go2shop
  jpa:
    show-sql: true
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  

img:
  upload-path: D:\ISS\project\go2shop\go2shop-app\src\assets\images\products\