server:
  port: 8763

spring:
  application:
    name: catalogue-service
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  