server:
  port: 8765

spring:
  application:
    name: payment-service
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  