server:
  port: 8766

spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/userdb?serverTimezone=GMT
    username: go2shop
    password: go2shop
  jpa:
    show-sql: true
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
      
feign:
  hystrix:
    enabled: true