eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8770
  
spring:
  application:
    name: gateway-springcloudgateway
  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: 'http://localhost:8780/rsa/publicKey'
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config
    gateway:
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/api/authenticationService/**
        filters:
        - RewritePath=/api/authenticationService/(?<segment>.*), /$\{segment}
      - id: cart-service
        uri: lb://cart-service
        predicates:
        - Path=/api/cartService/**
        filters:
        - RewritePath=/api/cartService/(?<segment>.*), /$\{segment}
      - id: catalogue-service
        uri: lb://catalogue-service
        predicates:
        - Path=/api/catalogueService/**
        filters:
        - RewritePath=/api/catalogueService/(?<segment>.*), /$\{segment} 
        
        
secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/api/authenticationService/oauth/token"
      
  authroities:
    - 
      urls:
        - "/api/cartService/cart/demo/**"
      roles:
        - BUYER
        - SELLER
        
    - 
      urls:
        - "/api/catalogueService/catalogue/demo/**"
      roles:
        - SELLER