eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
      
server:
  port: 8770
  
spring:
  application:
    name: gateway-springcloudgateway
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user-api/**
        filters:
        - RewritePath=/user-api/(?<segment>.*), /$\{segment}
      - id: event-service
        uri: lb://event-service
        predicates:
        - Path=/event-api/**
        filters:
        - RewritePath=/event-api/(?<segment>.*), /$\{segment}