eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8770
  
spring:
  application:
    name: gateway-springcloudgateway
#  rabbitmq:
#    host: ${spring.rabbitmq.host}
#    username: ${spring.rabbitmq.username}
#    password: ${spring.rabbitmq.password}
#    virtual-host: ${spring.rabbitmq.virtual-host}
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config
    gateway:
      routes:
      - id: cart-service
        uri: lb://cart-service
        predicates:
        - Path=/cart-api/**
        filters:
        - RewritePath=/cart-api/(?<segment>.*), /$\{segment}
      - id: catalogue-service
        uri: lb://catalogue-service
        predicates:
        - Path=/catalogue-api/**
        filters:
        - RewritePath=/catalogue-api/(?<segment>.*), /$\{segment}